### ISSUE TITLE
pycharm	开源免费的IDE???

### ISSUE THREAD

**Issue by daimiaopeng** [yunteng9345/parse-api#1]
有开源吗？

**Comment by yunteng9345** [comment]
开了吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunteng9345/parse-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 上午10:54
收件人:&nbsp;"yunteng9345/parse-api"<parse-api@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yunteng9345/parse-api] pycharm 开源免费的IDE??? (#1)





 
有开源吗？
